//--------------------------------------------------------------------------------------------------------------
// <auto-generated> 
//--------------------------------------------------------------------------------------------------------------
using System.Collections.Generic;
using System.IO;

namespace HomeZone.UiObjects
{
    public enum TeAppLanguage
    {
        English, German, Hungarian
    }

    public static class TcAppLangDependentStrings
    {
        public static TeAppLanguage CurrentLanguage { get; set; } = TeAppLanguage.German;

        public static string Missing
        {
            get {
                switch (CurrentLanguage)
                {
                    case TeAppLanguage.English:
                        return "Missing";
                    case TeAppLanguage.German:
                        return "Fehlt";
                    case TeAppLanguage.Hungarian:
                        return "";
                    default:
                        throw new System.Exception("Unsupported language");
                }
            }
        }

        public static string Incomplete
        {
            get {
                switch (CurrentLanguage)
                {
                    case TeAppLanguage.English:
                        return "Incomplete";
                    case TeAppLanguage.German:
                        return "Unvollständig";
                    case TeAppLanguage.Hungarian:
                        return "";
                    default:
                        throw new System.Exception("Unsupported language");
                }
            }
        }

        public static string CuttingProgram
        {
            get {
                switch (CurrentLanguage)
                {
                    case TeAppLanguage.English:
                        return "Cutting Program";
                    case TeAppLanguage.German:
                        return "Schneidprogramm";
                    case TeAppLanguage.Hungarian:
                        return "";
                    default:
                        throw new System.Exception("Unsupported language");
                }
            }
        }

        public static string TechnologyTableSelection
        {
            get {
                switch (CurrentLanguage)
                {
                    case TeAppLanguage.English:
                        return "Technology table selection";
                    case TeAppLanguage.German:
                        return "Technologietabellen Auswahl";
                    case TeAppLanguage.Hungarian:
                        return "Technológiatáblázatok kiválasztása";
                    default:
                        throw new System.Exception("Unsupported language");
                }
            }
        }

        public static string ReleaseMissing
        {
            get {
                switch (CurrentLanguage)
                {
                    case TeAppLanguage.English:
                        return "Release missing";
                    case TeAppLanguage.German:
                        return "Freigabe fehlt";
                    case TeAppLanguage.Hungarian:
                        return "";
                    default:
                        throw new System.Exception("Unsupported language");
                }
            }
        }
   
    }
}
